# Generated by Django 3.0.1 on 2020-04-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200328_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equation',
            name='first',
        ),
        migrations.RemoveField(
            model_name='equation',
            name='second',
        ),
        migrations.RemoveField(
            model_name='equation',
            name='type_equation',
        ),
        migrations.AlterField(
            model_name='equation',
            name='result',
            field=models.CharField(max_length=50),
        ),
    ]
