# Generated by Django 3.0.5 on 2020-05-02 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_remove_history_admin_id'),
        ('main', '0004_antiderivative'),
    ]

    operations = [
    ]
