# Generated by Django 3.0.1 on 2020-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20200502_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='equation',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='history',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='creation_time',
            field=models.CharField(max_length=35),
        ),
    ]
