# Generated by Django 3.0.1 on 2020-05-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200517_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='operation_type',
            field=models.CharField(max_length=55),
        ),
    ]
