# Generated by Django 3.0.1 on 2020-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200517_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='result',
            field=models.FloatField(),
        ),
    ]
